# 2021-11-13作业
姓名：姚罗然  
学号：2020810008  
### **参考内容**   
> [Markdown 官方教程](https://markdown.com.cn/)  
[NumPy 统计函数 | 菜鸟教程](https://www.runoob.com/numpy/numpy-tutorial.html)  
[NumPy 中文](https://www.numpy.org.cn/)  
[Pandas 教程 | 菜鸟教程](https://www.runoob.com/pandas/pandas-tutorial.html)  
[Pandas 中文](https://www.pypandas.cn/)  
课件

# NumPy

1. 请写出一种NumPy的安装方法。

```bash
pip install numpy
```

2. 请列出NumPy创建数组的两种方法。

In [1]:
import numpy as np

#1
array1 = np.array([1,2,3,4,5])
print(array1)

#2
array2 = np.zeros((2,5), int) 
print(array2)

[1 2 3 4 5]
[[0 0 0 0 0]
 [0 0 0 0 0]]


3. 请列出NumPy的两种属性。
> 应该是指NumPy数组的属性

In [2]:
#秩，即轴的数量或维度的数量
print(array1.ndim)
#数组的维度，对于矩阵，n 行 m 列
print(array2.shape)

1
(2, 5)


4. 请创建一个数组，并用一种切片方法对其切片。

In [3]:
print (array1[2::-1])

[3 2 1]


5. 请创建0到11的数组，并进行均等分割为两个等长的数组。

In [4]:
array3 = np.arange(10)
np.split(array3, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

6. 请创建0到6的数组，并计算其总和。

In [5]:
array4 = np.arange(6)
np.sum(array4)

15

# pandas

1. 请写出一种pandas的安装方法。

```bash
pip install Pandas
```

2. 请写出pandas的两种数据结构，并写出它们各自的一种创建方法。

In [6]:
import pandas as pd

#1. Series (opens new window)是带标签的一维数组，可存储整数、浮点数、字符串、Python 对象等类型的数据。轴标签统称为索引。
s = pd.Series([1,2,3,4,5])
print(s)

#2. DataFrame 是由多种类型的列构成的二维标签数据结构，类似于 Excel 、SQL 表，或 Series 对象构成的字典。
d1 = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df1 = pd.DataFrame(d1)
print(df1)

0    1
1    2
2    3
3    4
4    5
dtype: int64
   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0


3. 请写出读取excel文件和读取mysql数据的方法。

In [7]:
#Excel
df_excel = pd.read_excel('pandas_demo.xlsx', sheet_name='Sheet1')
print(df_excel)

#MySQL
import pymysql
mysql_cn = pymysql.connect(host="localhost", user="root", password="pythonclass", db="g9yaoluoran", charset='utf8')
df_mysql = pd.read_sql('select * from g9yaoluoran;', con=mysql_cn)    
mysql_cn.close()
print(df_mysql)

     列1   列2   列3   列4   列5   列6   列7   列8   列9
0   111  222  333  444  555  666  777  888  900
1   112  223  334  445  556  667  778  889  901
2   113  224  335  446  557  668  779  890  902
3   114  225  336  447  558  669  780  891  903
4   115  226  337  448  559  670  781  892  904
5   116  227  338  449  560  671  782  893  905
6   117  228  339  450  561  672  783  894  906
7   118  229  340  451  562  673  784  895  907
8   119  230  341  452  563  674  785  896  908
9   120  231  342  453  564  675  786  897  909
10  121  232  343  454  565  676  787  898  910
11  122  233  344  455  566  677  788  899  911
12  123  234  345  456  567  678  789  900  912
13  124  235  346  457  568  679  790  901  913
14  125  236  347  444  569  680  791  902  914
      majorid      deptid majorname majorassistant     majortel
0  2020810008  2020810008      临床医学            姚罗然  15362330731


4. 请创建一个两行三列的Dataframe，并用自己姓名的拼音替换掉其中某一个值。

In [8]:
d2 = [{'a': 1, 'b': 2, 'c':3}, {'a': 5, 'b': 10, 'c': 20}]
df2 = pd.DataFrame(d2)
print(df2)

df2.at[[1],'b'] = 'yaoluoran'
print(df2)

   a   b   c
0  1   2   3
1  5  10  20
   a          b   c
0  1          2   3
1  5  yaoluoran  20
